### ISSUE TITLE
Incorrect Color Mode?

### ISSUE THREAD

**Issue by duckydee** [Cookleplex/DuckGame-MetaPixel-Editor#1]
I try to load in a duck game hat I'm making with some metapixels in it already, but it keeps saying that the file's color mode is wrong. How can I fix that?

**Comment by Cookleplex** [comment]
Can you upload the hat file so I can take a look at it, also I'm trying to get a new version out currently the blue color value doesn't work!

**Comment by Cookleplex** [comment]
I got the new version out just an FYI

**Comment by duckydee** [comment]
![panduck](https://user-images.githubusercontent.com/31322692/100016935-2432d980-2da8-11eb-9890-e2fbdcf44272.png)
Here's my hat file I'm trying to use, I just tried the latest version and it doesnt work with my hat.

**Comment by Cookleplex** [comment]
Ok that image is in palleted mode which takes up a third of the space but doesn't work with the current version of the program. Here's a version I converted to RGBA for you, in future releases this should be automated.
![hat](https://user-images.githubusercontent.com/51760498/100017621-0e191f00-2d90-11eb-94b2-e6ccd4569d9d.png)

**Comment by duckydee** [comment]
Oh neat that works! Any way I can convert to RGBA in something like paint.net?

**Comment by Cookleplex** [comment]
If you open it in paint3d & save it from the test I just did it should convert its format.

**Comment by Cookleplex** [comment]
I've fixed the issue & it'll be added to newer versions, but for now just use paint3d or something else to convert
